### ISSUE TITLE
collection.countDocuments is undefined

### ISSUE THREAD

**Issue by ashantyk** [williamkapke/mongo-mock#100]
recent versions of the mongodb driver have deprecated the collection.count() method in favor of collection.countDocuments() and collection.estimatedDocumentCount().

trying mock modern apps that use the collection.countDocuments() method end up throwing 'countDocuments is undefined' errors.

**Comment by ashantyk** [comment]
https://github.com/williamkapke/mongo-mock/pull/102

**Comment by williamkapke** [comment]
Awesome THanks! Merged
