### ISSUE TITLE
deleteMany does not properly manage promises

### ISSUE THREAD

**Issue by gabmontes** [williamkapke/mongo-mock#105]
If the `callback` parameter is not set when calling `deleteMany`, the function does not return a promise.

The issue is the check for `callback` is done inside the callback for `cursor()` instead of doing so at `deleteMany` function level.

**Comment by zardilior** [comment]
Yes it does not :(

**Comment by shaunburdick** [comment]
#109 for your review. 😉

**Comment by zardilior** [comment]
@shaunburdick I ll be testing now with my code :D

**Comment by kirkoman** [comment]
Here is one random person voting for this fix to be merged.

**Comment by shaunburdick** [comment]
I can merge it but I can't cut a release, so I guess technically your vote is my command ;-)

**Comment by NitroBAY** [comment]
Wait why you can't "cut the release" ?
"your vote is my command" ? I vote to release if it's what you asking for. This is a pretty critical issue that took me a lot of time to debug.

**Comment by williamkapke** [comment]
@shaunburdick you should be able to `npm publish`. I just double checked and you Do have write access to NPM. I really want to make sure there is publish redundancy. (Ya know- that "Bus" factor thing)

Can you give it a try? Looks like the version number needs a bump.

**Comment by ronkorving** [comment]
There are a few more open PRs that were approved but not merged. Please consider :)

**Comment by shaunburdick** [comment]
Yeah, I'll give it a shot tomorrow. Review the prs, bump the version and release. I didn't realize I had npm access

**Comment by shaunburdick** [comment]
v3.9.0 should be out the door

**Comment by williamkapke** [comment]
Awesome! Thank you 😊
