### ISSUE TITLE
Mixed projections types not allowed

### ISSUE THREAD

**Issue by purefan** [williamkapke/mongo-mock#120]
Hey guys!

Loving the project, it allows me to really test my express app from a mocha testsuite but today I ran into an issue when I was refactoring, this query:
```
db.getCollection('position').findOne({
            status: 0
        }, {
            sort: [ [ 'priority', 'desc' ] ]
        })
```

works against a normal mongo database, but in mongo-mock it fails with:
> mongo-mock:collection findOne {"query":{"status":0},"fields":{"sort":[["priority","desc"]]},"skip":0,"limit":0} callback=undefined +0ms
>  mongo-mock:cursor initializing cursor +0ms
> Error: Mixed projections types not allowed

Is it something Im doing wrong?

**Comment by williamkapke** [comment]
The 2nd parameter is a projection (an object that says which fields to return). Your query's 2nd parameter tries to sort ... mongo-mock is getting confused with it.



I suspect real mongo isn't sorting and is just ignoring it..? not sure.

**Comment by purefan** [comment]
I changed the way I was querying based on your feedback and it works now, I havent confirmed that mongo wasnt sorting but I expected an error from mongo, it just never came and I thought my code was fine.

Thanks for your feedback! loving the project <3
