### ISSUE TITLE
MongoClient.connect() doesn't exist like mongodb's one

### ISSUE THREAD

**Issue by danosaure** [williamkapke/mongo-mock#14]
Hi,

I have noticed the following issue. When the connection is not closed, the script never exits. I am not arguing that I should not have a `finally`, just that I did not expect this difference.

Thanks,

```
$ cat mongodb-connect.js
const mongodb = require('mongodb');
mongodb.MongoClient.connect('mongodb://dummy-host/')
    .then((db) => console.log("Connected mongo-mock"));

$ node mongodb-connect.js
(node:38853) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [dummy-host:27017] on first connect

$ cat mongo-mock-connect.js
const mongodb = require('mongo-mock');
mongodb.MongoClient.connect('mongodb://dummy-host/')
    .then((db) => console.log("Connected mongodb"));

$ node mongo-mock-connect.js
Connected mongodb
^C
```

**Comment by shaunburdick** [comment]
If I'm reading this right, it looks like your `mongodb-connect.js` isn't connecting to the dummy-host (assuming that's expected by the name)
`mongo-mock` simulates a connection to a mongodb instance so it assumes the connection url is a valid db and pretends to be connected to it.

**Comment by danosaure** [comment]
That is not what I am mentioning here. I'm saying that, unless I have `db.close()`, the script never ends, unlike with the real `mongodb` library. As you can see above, I do not need to `^C` for the `node mongodb-connect.js` to exit.

**Comment by shaunburdick** [comment]
Right but `mongodb-connect.js` isn't actually connecting to a database. It's failing and you're not catching the promise rejection. `mongo-mock-connect.js` will always "connect" and you must close the connection before exiting your application.

**Comment by danosaure** [comment]
I'm sorry, I'm trying to point out a difference, and all you are trying to do is divert the discussion. If I did not catch the rejection as you suggest, should it break? Anyways, I don't feel like you are understanding what I am saying.
