### ISSUE TITLE
Adding on a new maintainer

### ISSUE THREAD

**Issue by LinusU** [williamkapke/mongo-mock#149]
Hello @williamkapke,

I currently have quite a few open pull requests, and are maintaining my own fork which have all of those merged in. It would be great to be able to get these in upstream so that everyone can benefit from the same codebase.

Would you be open to adding me on as a maintainer? I'm [`linusu` on Npm](https://www.npmjs.com/~linusu)

**Comment by williamkapke** [comment]
👍 

Great! I sent you an Invite. Thanks for your contributions- I'm very glad you have you help out.

Please check out:
https://github.com/williamkapke/mongo-mock/issues/71#issuecomment-412207494

**Comment by LinusU** [comment]
Awesome, thank for the quick invite!

I've accepted the Github invite, and will read thru #71 as well 👍

**Comment by williamkapke** [comment]
Just added you on NPM. You should be all set!
