### ISSUE TITLE
Documents cleanup between test cases

### ISSUE THREAD

**Issue by htbkoo** [williamkapke/mongo-mock#27]
Hi, thanks a lot for creating this package! It is really useful for unit tests or for doing some quick hacks.

However I would like to ask if there is an API to clean up the in-memory database/documents between few test cases in one test suite (apologies but seems this is not mentioned in the readme or in other issues)?

Or should I call the remove() to clean up?

Thank you. :)

**Comment by williamkapke** [comment]
Check out this comment:
https://github.com/williamkapke/mongo-mock/issues/8#issuecomment-280756829

... will that work for you?

**Comment by htbkoo** [comment]
Sorry I was busy yesterday and had no time to test it out.
But yes I think it works for truncating - do you want me to create a pull request for adding a small section for this in the read me?

Anyway, thanks! :)

**Comment by williamkapke** [comment]
yeah! That'd be great!
