### ISSUE TITLE
collection.find() is returning the wrong type

### ISSUE THREAD

**Issue by d-theo** [williamkapke/mongo-mock#4]
Hi, 
I'm trying to mock with mongo-mock but the collection.find() method is returning me an array of object instead of a cursor like mongo (using mongodb package 2.0.49)

**Comment by williamkapke** [comment]
Thanks for pointing that out. I've been meaning to get this updated with Promises anyhow- so I rolled it all in. Try it out- hope it works for you. Let me know!

**Comment by d-theo** [comment]
thanks for your reactivity, it's working like a charm
I'll keep following the lib :)
