### ISSUE TITLE
Bug: update after upsert does not work

### ISSUE THREAD

**Issue by IhostVlad** [williamkapke/mongo-mock#46]
If some document had been inserted into collection by upsert method (update with upsert flag option), when it can't be updated later.

Example code:
```javascript
collection.update({ key: 'KEY' }, { key: 'KEY', value: 'VALUE-1' }, { upsert: true }, (err1) => {
  collection.update({ key: 'KEY' }, { key: 'KEY', value: 'VALUE-2' }, (err2) => {
    const document = collection.findOne({ key: 'KEY' }, (err3, doc) => {
      if(err1 || err2 || err3) {
        console.log('Error occured: ', err1, err2, err3);
      } else {
        console.log('Document: ', document);
      }
    })
  })
})
```

After execution, `{ key: 'KEY', value: 'VALUE-1' }` will be printed. But valid result is `{ key: 'KEY', value: 'VALUE-2' }`

**Comment by williamkapke** [comment]
`update` was not allowing updates without using `$set` unless it was an upsert :(

By integrating modifyjs (see #45), it corrected this. 🍻 Thanks for reporting this!
