### ISSUE TITLE
mocha does not exit after closing connection to mock mongodb

### ISSUE THREAD

**Issue by lspliner** [williamkapke/mongo-mock#48]
On line # 162 of db.js there is a call to setTimeout that is supposed to keep hosting process running until at least one connection is open .

```javascript
open = setInterval(function () {}, 600000)
```

In order to let process exit when connections are closed there is a corresponding line # 26 at db.js

```javascript
clearInterval(open);
```

But setTimeout is called twice when I run MongoClient.connect. So one of two timers stays scheduled and mocka keeps running after closing connection to mock mongodb.

**Comment by lspliner** [comment]
Debug output. Highlighted are lines corresponding to opening and closing connections.

Tue, 23 Jan 2018 09:31:34 GMT mongo-mock:mongo_client connecting 127.0.0.1:27017/calculator
Tue, 23 Jan 2018 09:31:34 GMT mongo-mock:collection initializing instance of `system.namespaces` with 1 documents
Tue, 23 Jan 2018 09:31:34 GMT mongo-mock:collection initializing instance of `system.indexes` with 0 documents
**Tue, 23 Jan 2018 09:31:34 GMT mongo-mock:db calculator open**
Tue, 23 Jan 2018 09:31:35 GMT mongo-mock:collection initializing instance of `ratio` with undefined documents
Tue, 23 Jan 2018 09:31:35 GMT mongo-mock:collection insert [{"sheet":{"key":"a95d94bd-290d-46bf-ab90-21b191a0a6b5"},"created_at":"2018-01-23T09:31:35.659Z"}]
**Tue, 23 Jan 2018 09:31:35 GMT mongo-mock:db calculator open**
Tue, 23 Jan 2018 09:31:36 GMT mongo-mock:db ratio persist() - creating _id index
Tue, 23 Jan 2018 09:31:36 GMT mongo-mock:collection findOne {"query":{"_id":"5a6700f8eed94d1914f8256f"},"fields":{},"skip":0,"limit":0} callback=function
Tue, 23 Jan 2018 09:31:36 GMT mongo-mock:cursor initializing cursor
**Tue, 23 Jan 2018 09:31:36 GMT mongo-mock:db closing calculator**

**Comment by lspliner** [comment]
Sorry, it was my fault.

**Comment by rjmunhoz** [comment]
I hate to revive this, but @lspliner, could you provide details on how you solved this?
I'm having the same problem, and I don't get why it's being called twice

**Comment by grmmph** [comment]
I have the same issue

**Comment by grmmph** [comment]
https://github.com/williamkapke/mongo-mock/pull/127

**Comment by shaunburdick** [comment]
You need to make sure you call the `close()` function.
