### ISSUE TITLE
Deep merge on updateOne

### ISSUE THREAD

**Issue by yaplas** [williamkapke/mongo-mock#55]
When you update an item the expected result is a shallow merge but it is doing a deep merge:
<img width="669" alt="2018-04-10_1210" src="https://user-images.githubusercontent.com/2750777/38834440-e309f814-419e-11e8-94f3-4c3bee3995e4.png">

Expected result is just {value: {c: 2}}

I think the issue is in this line:
https://github.com/williamkapke/mongo-mock/blob/master/lib/collection.js#L436
Instead of use `_.merge` you have to use `_.assign`

**Comment by AngefloMusic** [comment]
I have added support for deep merge in my PR

**Comment by pludov** [comment]
@AngefloMusic: I reproduce the issue, even using the branch of your PR. (You're correction seems to target upsert only indeed.)

The fix to replace merge with assign seems ok to me - I created a PR: https://github.com/williamkapke/mongo-mock/pull/72

**Comment by AngefloMusic** [comment]
v3.3.1 fixed this :)
