### ISSUE TITLE
"interface is a reserved word in strict mode"

### ISSUE THREAD

**Issue by wjagodfrey** [williamkapke/mongo-mock#59]
Getting a strict mode error when checked out locally:

`interface is a reserved word in strict mode`

Happy to open a PR for this if someone can give me a better alternative.

**Comment by williamkapke** [comment]
I've seen others use `iface`. Feel free to pick something- PR very welcome. 👍

**Comment by AngefloMusic** [comment]
@wjagodfrey if this is still an issue there's a refactor coming down the pipeline that I could tackle this in.

**Comment by Pidid** [comment]
@AngefloMusic I think we should use `iface` as the naming standard instead of `interface`. If you agree then I'll go through and refactor, then close this issue.

**Comment by AngefloMusic** [comment]
I agree, I'll put something in now

**Comment by Pidid** [comment]
#82 fixes this. `iface` is now the standard
