### ISSUE TITLE
MongoClient.connect failed to return db for non-callback.

### ISSUE THREAD

**Issue by vincentleekp** [williamkapke/mongo-mock#7]
for mongdodb, MongoClient allow to call the connection "MongoClient.connect(url)" without callback function provided. This mock have issue for this scenario. 

Found is missing 'return' for below code:
lib/mongo_client.js line 22
**return** new Db(dbname, server).open(callback);

**Comment by vincentleekp** [comment]
Any update?

**Comment by williamkapke** [comment]
Sorry- I was traveling :(

It looks like the callback is required:
https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#MongoClient.connect

Maybe I am misunderstanding?

**Comment by mysticatea** [comment]
http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html
http://mongodb.github.io/node-mongodb-native/2.2/api/lib_mongo_client.js.html#line88

If `callback` is omitted, it returns a `Promise`.

**Comment by williamkapke** [comment]
Oh- right, yes in v2+ it returns a Promise. Now I understand what the issue is all about! :)

Any interest in submitting a PR? I'm traveling around Europe for Node conferences and I don't know that I'll get to this very fast :/

**Comment by mysticatea** [comment]
I'm sorry, I don't have enough time for this issue (my OSSs and eslint have higher priority in my time).

**Comment by mnmtanish** [comment]
Any updates? I've opened a pull request (#9) with the change mentioned above. Please let me know if there's anything else.
