### ISSUE TITLE
A lack of mantanience on this project

### ISSUE THREAD

**Issue by AngefloMusic** [williamkapke/mongo-mock#71]
I've had some pending PR's for the last two months with no input, it's completely understandable if you're too busy @williamkapke as acting representation on the Node.js Board of Directors.

I'm opening this as a discussion as to whether to move the project forward and continue to add features, I should branch it, or instead have more people added to this project as moderators, that have the time to discuss and review Pull Requests.

Thanks for hearing me out!
Angelo

**Comment by Pidid** [comment]
@AngefloMusic thank you for opening this! I am in the same boat as you.

I have had a pending PR for about a month, as well as some other changes on my fork that I haven't yet made PR's for (due to the lack of activity with maintenance here). This project has been of great use to me, my friends, and my coworkers. I would love to see this project eventually fully mock the mongodb API and I would also love to moderate and heavily contribute to this project.

Excited to see where this goes!

**Comment by AngefloMusic** [comment]
@Pidid Same here! We use it for our automated testing suite, and I've added several features/fixed the way they performed, to be fully featured, and with 4.0 supporting ACID, I'd like to continue adding more features.

**Comment by williamkapke** [comment]
Hey folks. Guilty as charged.

A few months back, I recognize that I was not going to be available much of the summer with personal things. Indeed- the free time I have is committed to my work on the Node.js Board.

I reached out to a few folks looking for help - but, understandably, they were already too overloaded with other tasks.

This is FANTASTIC news to hear you're using it and found it helpful! I apologize for procrastinating this epically.

I also use this project for testing and depend on it- so I want it to succeed too! I do not have a personal "ownership" connection I want to maintain: meaning, I'd like it to be fully owned by several people that can collaborate and make it 💯 

Here's what I'm hoping for:
- Min 2 collaborators.
- PRs are approved by someone other than the original author-- and that doesn't work for the same company. (this helps to ensure something specific functionally doesn't creep in that is only useful for 1 company!)
- Try VERY hard to keep parity with the real Mongo.
- Grant access to min 2 people that can publish to NPM.
- Try to keep supporting old and new Mongo versions.

I really appreciated the help folks have given (extra shoutout to @shaunburdick) getting this project this far!

Please let me know if you're interested in becoming a collaborator. 🙏

**Comment by Pidid** [comment]
Glad for the response! You sound pretty busy, so the lack of activity is understandable. I am totally interested in becoming a collaborator.

Sounds like @AngefloMusic and I would make getting the minimum 2 collaborators easy ;). We don't work together, both want to see this project move forward, and both of us seem to try to mimic mongodb as closely as possible in our PR's. In fact, my Bulk Operation PR, I mention wanting to  go through the mongodb source to see exactly how they do bulk operations and then implementing it into mongo-mock.

Anyways, definitely want to help and thanks again for the quick response!

**Comment by AngefloMusic** [comment]
@williamkapke Thank you for such a prompt and detailed response! I'm 100% interested in becoming a collaborator, I agree with all of these milestones, and want to get as close to real mongo as possible to create a seamless testing experience! It is true @Pidid do not know each other beyond both wanting to see this project moving forward be successful! I'd also like to implement more BulkOperations features (for example upsert support)

I'd be glad to help out, just let me know what I have to do moving forward in order to get access to these things (github permissions, and NPM publish access) .

Feel free to reach out to me via email for some of this stuff.

**Comment by Pidid** [comment]
@williamkapke Yeah my email is just on my github as well 👍.

**Comment by williamkapke** [comment]
Ok. You are both Collaborators now!

Please be open to:
- inviting more people
- setting standards
- Improving the readme/coding standards/etc...
  - Add a Collaborators section?
  - Give props to the great projects that do some pretty heavy lifting for us:
    - @crcn's [sift.js](https://github.com/crcn/sift.js)
    - @lgandecki's [modifyjs](https://github.com/lgandecki/modifyjs)

**Comment by AngefloMusic** [comment]
Going to officially close this now the ball is rolling! 😄
