### ISSUE TITLE
Provide a simple API to insert test data into the fake DB

### ISSUE THREAD

**Issue by BenoitAverty** [williamkapke/mongo-mock#8]
When using mongo-mock inside unit tests for example, it's a bit tedious to use the mongodb api to insert data (MongoClient.connect, with callback hell and everything else).

It would be great to have a simple, synchronous API to insert test data and clear everything.

Here's an example of what I have in mind:

``` javascript
import mongoMock from 'mongo-mock';

beforeEach(() => {
    mongoMock.clearTestData();
    mongoMock.insertTestData('collection', [...data]);
    // Or maybe...
    mongoMock.insertTestData('dbUri', 'collection', [...data]);
});
```

I don't know if it's possible in your library, but that would make writing test way easier.

**Comment by gyowanny** [comment]
I agree with BenoitAverty that it would be nice to have such features, specially to truncate collections.

**Comment by williamkapke** [comment]
You can call `.toJSON()` to get access to the underlying `state` object. From there you can do anything to the `documents` array (or any of the state info) that you want. But be aware that you're bypassing any conflict checks! (like a primary key)

```js
var collection = db.collection('foo');
var state = collection.toJSON()
// Do whatever you want. It's just an Array of Objects.
state.documents.push({a : 2})

// truncate
state.documents.length = 0
```

**Comment by ChrisCinelli** [comment]
I think that you should have an efficient `loadFixture(collection, file, opt)` function.

**Comment by AngefloMusic** [comment]
I think this could finally be closed with the addition of BulkOperations support in #67 !

**Comment by Pidid** [comment]
@AngefloMusic Agreed. I'll close this for now.
